name: API Documentation Check

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.py'
      - '.github/workflows/api_doc_check.yml'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check_doc_updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- '**/*.py' || git diff --name-only HEAD^ HEAD -- '**/*.py')
          if [ -n "$CHANGED_FILES" ]; then
            echo "files<<EOF" >> $GITHUB_OUTPUT
            echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Test API key
        run: python scripts/test_api.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Process changes
        run: |
          while IFS= read -r file; do
            if [ -n "$file" ]; then
              echo "Analyzing changes in $file"
              python scripts/analyze_py_changes.py "$file"
            fi
          done <<< "${{ steps.changed-files.outputs.files }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
