name: Documentation Check

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**/*.py'
      - 'src/**/README.md'

jobs:
  check-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyGithub

    - name: Check README Updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        MODIFIED_FILE=$(git diff --name-only HEAD^ HEAD -- 'src/**/*.py' | head -n 1)
        if [ -n "$MODIFIED_FILE" ]; then
          python scripts/analyze_py_changes.py "$MODIFIED_FILE"
        fi
