name: API Documentation Update

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - closed

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Get list of modified files
        run: |
          git diff --name-only HEAD~1 > modified_files.txt

      - name: Analyze Python Changes
        run: |
          while IFS= read -r file; do
            if [[ $file == *.py ]]; then
              python scripts/analyze_py_changes.py "$file"
            fi
          done < modified_files.txt

      - name: Run API Documentation Update
        run: node scripts/update_docs.js

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b docs-update-$(date +%s)
          git add .
          git commit -m "chore: Automatically update API documentation"
          git push origin HEAD